name: Build Plugin

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
      - 'V*'
      - '[0-9]+*'
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies & Build
        run: dotnet build --configuration ReleaseNoDeps

      - name: Run Tests
        run: dotnet test --configuration Release
