name: Build Plugin

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*.*.*'
      - '*.*.*'
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies & Build
        run: dotnet build --configuration ReleaseNoDeps

      - name: Run Tests
        run: dotnet test --configuration Release

      - name: Upload WankulCrazyPlugin.dll Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WankulCrazyPlugin
          path: dist/WankulCrazy/WankulCrazyPlugin.dll

      - name: Create Release / Pre-release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/WankulCrazy/WankulCrazyPlugin.dll
          prerelease: ${{ contains(github.ref_name, '-') }}
          generate_release_notes: true
